const arrTasks = [
  {
    id: '155',
    name: 'Создать логотип приложения',
    description: 'Формат изображения – svg, размеры - 100х100px',
    createdAt: new Date('2023-03-09T23:00:00'),
    assignee: 'Иванов',
    status: 'To Do',
    priority: 'High',
    isPrivate: false,
    comments: [
      {
        id: '912',
        text: 'Будет сделано!',
        createdAt: new Date('2023-03-09T23:00:00'),
        author: 'Иванов',
      },
    ],
  },
  {
    id: '1',
    name: 'Создать логотип приложения',
    description: 'Формат изображения – svg, размеры - 100х100px',
    createdAt: new Date('2023-03-09T23:00:00'),
    assignee: 'Иванов',
    status: 'Complete',
    priority: 'High',
    isPrivate: false,
    comments: [
      {
        id: '912',
        text: 'Будет сделано!',
        createdAt: new Date('2023-03-09T23:00:00'),
        author: 'Иванов',
      },
    ],
  },
  {
    id: '2',
    name: 'Переименовать константу DELAY_TIME ',
    description:
     'Необходимо переименовать константу с DELAY_TIME на DELAY_API_TIME',
    createdAt: new Date('2023-03-09T23:00:00'),
    assignee: 'Иванов',
    status: 'To Do',
    priority: 'High',
    isPrivate: false,
    comments: [
      {
        id: '912',
        text: 'Будет сделано!',
        createdAt: new Date('2023-03-09T23:00:00'),
        author: 'Иванов',
      },
    ],
  },
  {
    id: '3',
    name: 'Разработать дизайн ',
    description: 'Необходимо разработать дизайн приложения',
    createdAt: new Date('2023-02-09T23:00:00'),
    assignee: 'Петров',
    status: 'In progress',
    priority: 'Low',
    isPrivate: true,
    comments: [
      {
        id: '9120',
        text: 'Будет сделано!',
        createdAt: new Date('2023-02-09T23:00:05'),
        author: 'Петров',
      },
    ],
  },
  {
    id: '4',
    name: 'Разработать бургер-меню',
    description: 'Разработать бургер-меню',
    createdAt: new Date('2023-01-09T23:00:00'),
    assignee: 'Коршунов',
    status: 'In progress',
    priority: 'Medium',
    isPrivate: false,
    comments: [
      {
        id: '9121',
        text: 'Ok',
        createdAt: new Date('2023-01-09T23:00:05'),
        author: 'Коршунов',
      },
    ],
  },
  {
    id: '5',
    name: 'Разработать модалку',
    description: 'Сделать модалку',
    createdAt: new Date('2023-01-12T23:00:00'),
    assignee: 'Ермолаева',
    status: 'Complete',
    priority: 'Low',
    isPrivate: false,
    comments: [
      {
        id: '9122',
        text: 'Срочно!',
        createdAt: new Date('2023-01-12T23:00:05'),
        author: 'Коршунов',
      },
    ],
  },
  {
    id: '6',
    name: 'Протестировать бургер-меню',
    description: 'Протестировать бургер-меню на разных разрешениях',
    createdAt: new Date('2023-01-15T23:00:00'),
    assignee: 'Буян',
    status: 'To Do',
    priority: 'Low',
    isPrivate: true,
    comments: [
      {
        id: '9123',
        text: 'Это не срочно, но важно!',
        createdAt: new Date('2023-01-15T23:00:05'),
        author: 'Коршунов',
      },
    ],
  },
  {
    id: '7',
    name: 'Сделать адаптив',
    description: 'Сделать адаптивную версию дизайна',
    createdAt: new Date('2023-02-15T23:00:00'),
    assignee: 'Варан',
    status: 'In progress',
    priority: 'Medium',
    isPrivate: true,
    comments: [
      {
        id: '9124',
        text: 'Это не срочно, но важно!',
        createdAt: new Date('2023-01-15T23:00:05'),
        author: 'Коршунов',
      },
      {
        id: '9125',
        text: 'Не забудь проо логотип!',
        createdAt: new Date('2023-02-15T23:00:05'),
        author: 'Варан',
      },
    ],
  },
  {
    id: '8',
    name: 'Разработать слайдер',
    description: 'Сделать слайдер под фотографии',
    createdAt: new Date('2023-02-11T23:00:00'),
    assignee: 'Белусь',
    status: 'To Do',
    priority: 'Medium',
    isPrivate: false,
    comments: [
      {
        id: '912',
        text: 'Это не срочно, но важно!',
        createdAt: new Date('2023-01-12T23:00:05'),
        author: 'Коршунов Илья',
      },
      {
        id: '912',
        text: 'Не забудь про новые форматы!',
        createdAt: new Date('2023-02-15T23:00:05'),
        author: 'Варан Саша',
      },
    ],
  },
  {
    id: '9',
    name: 'Разработать пагинацию',
    description: 'Сделать пагинацию основной страницы',
    createdAt: new Date('2023-01-19T23:00:00'),
    assignee: 'Варяг',
    status: 'In progress',
    priority: 'Low',
    isPrivate: true,
    comments: [
      {
        id: '912',
        text: 'Будет сделано!',
        createdAt: new Date('2023-03-09T23:00:05'),
        author: 'Иванов',
      },
    ],
  },
  {
    id: '10',
    name: 'Сделать авторизацию',
    description: 'Сделать авторизацию пользователя на главной странице',
    createdAt: new Date('2023-02-20T23:00:00'),
    assignee: 'Симан',
    status: 'Complete',
    priority: 'High',
    isPrivate: false,
    comments: [
      {
        id: '9129',
        text: 'Это не срочно, но важно!',
        createdAt: new Date('2023-01-20T23:00:05'),
        author: 'Коршунов Илья',
      },
      {
        id: '9130',
        text: 'Не забудь проо логотип!',
        createdAt: new Date('2023-02-15T23:00:05'),
        author: 'Варан Саша',
      },
    ],
  },
  {
    id: '11',
    name: 'Сделать страницу админа',
    description: 'Сделать страницу админа для администрирования сайта',
    createdAt: new Date('2023-01-20T23:00:00'),
    assignee: 'Горян',
    status: 'In progress',
    priority: 'Low',
    isPrivate: false,
    comments: [
      {
        id: '9135',
        text: 'Это не срочно, но важно!',
        createdAt: new Date('2023-01-20T23:00:05'),
        author: 'Коршунов Илья',
      },
    ],
  },
  {
    id: '12',
    name: 'Сделать страницу 404',
    description: 'Сделать страницу 404',
    createdAt: new Date('2023-03-20T23:00:00'),
    assignee: 'Ткачук',
    status: 'To Do',
    priority: 'Medium',
    isPrivate: true,
    comments: [
      {
        id: '9136',
        text: 'Это не срочно, но важно!',
        createdAt: new Date('2023-03-20T23:00:05'),
        author: 'Коршунов Илья',
      },
    ],
  },
  {
    id: '13',
    name: 'Разработать header',
    description: 'Разработать header для всех страниц',
    createdAt: new Date('2022-12-22T23:00:00'),
    assignee: 'Шук',
    status: 'To Do',
    priority: 'Low',
    isPrivate: false,
    comments: [
      {
        id: '9137',
        text: 'Это не срочно, но важно!',
        createdAt: new Date('2022-12-25T23:00:05'),
        author: 'Коршунов Илья',
      },
    ],
  },
  {
    id: '14',
    name: 'Разработать footer',
    description: 'Разработать footer для всех страниц',
    createdAt: new Date('2022-12-25T23:00:00'),
    assignee: 'Сидоренко',
    status: 'To Do',
    priority: 'Medium',
    isPrivate: false,
    comments: [
      {
        id: '9138',
        text: 'Это не срочно, но важно!',
        createdAt: new Date('2022-12-25T23:00:05'),
        author: 'Коршунов Илья',
      },
    ],
  },
  {
    id: '15',
    name: 'Разработать navigation',
    description: 'Разработать navigation для всех страниц',
    createdAt: new Date('2022-12-27T23:00:00'),
    assignee: 'Сидоренко',
    status: 'In progress',
    priority: 'High',
    isPrivate: false,
    comments: [
      {
        id: '9139',
        text: 'Это не срочно, но важно!',
        createdAt: new Date('2022-12-27T23:00:05'),
        author: 'Коршунов Илья',
      },
    ],
  },
  {
    id: '16',
    name: 'Разработать aside',
    description: 'Разработать aside для главной страницы',
    createdAt: new Date('2022-02-27T23:00:00'),
    assignee: 'Ткач',
    status: 'Complete',
    priority: 'Medium',
    isPrivate: false,
    comments: [
      {
        id: '9140',
        text: 'Это не срочно, но важно!',
        createdAt: new Date('2022-02-27T23:00:05'),
        author: 'Коршунов Илья',
      },
    ],
  },
  {
    id: '17',
    name: 'Сверстать confirm modal',
    description:
     'Разработать confirm modal в соответствии с дизайном приложения',
    createdAt: new Date('2022-02-28T23:00:00'),
    assignee: 'Петров',
    status: 'To Do',
    priority: 'Low',
    isPrivate: true,
    comments: [
      {
        id: '9141',
        text: 'Это не срочно, но важно!',
        createdAt: new Date('2022-02-29T23:00:05'),
        author: 'Коршунов Илья',
      },
    ],
  },
  {
    id: '18',
    name: 'Сверстать главную страницу',
    description:
     'Сверстать главную страницу в соответствии с дизайном приложения',
    createdAt: new Date('2022-01-28T23:00:00'),
    assignee: 'Петров',
    status: 'To Do',
    priority: 'Medium',
    isPrivate: true,
    comments: [
      {
        id: '9142',
        text: 'Это не срочно, но важно!',
        createdAt: new Date('2022-01-29T23:00:05'),
        author: 'Коршунов Илья',
      },
    ],
  },
  {
    id: '19',
    name: 'Сверстать страницу регистрации',
    description:
     'Сверстать страницу регистрации в соответствии с дизайном приложения',
    createdAt: new Date('2022-01-29T23:00:00'),
    assignee: 'Васильев',
    status: 'In progress',
    priority: 'High',
    isPrivate: false,
    comments: [
      {
        id: '9143',
        text: 'Это не срочно, но важно!',
        createdAt: new Date('2022-01-29T23:00:05'),
        author: 'Коршунов Илья',
      },
    ],
  },
  {
    id: '20',
    name: 'Проверить макет на соответствие ТЗ',
    description: 'Проверить все страницы макета на соответствие ТЗ ',
    createdAt: new Date('2022-01-30T23:00:00'),
    assignee: 'Васильев',
    status: 'Complete',
    priority: 'High',
    isPrivate: false,
    comments: [
      {
        id: '912',
        text: 'Будет сделано!',
        createdAt: new Date('2023-03-09T23:00:05'),
        author: 'Иванов',
      },
    ],
  },
  {
    id: '21',
    name: 'Проверить макет ',
    description: 'Проверить все страницы макета',
    createdAt: new Date('2022-01-30T23:00:00'),
    assignee: 'Васильев',
    status: 'Complete',
    priority: 'Low',
    isPrivate: false,
    comments: [
      {
        id: '912',
        text: 'Будет сделано!',
        createdAt: new Date('2023-03-09T23:00:05'),
        author: 'Иванов',
      },
    ],
  },
  {
    id: '22',
    name: 'Сверстать страницу авторизации',
    description:
     'Сверстать страницу авторизации',
    createdAt: new Date('2022-01-29T23:00:00'),
    assignee: 'Васильев',
    status: 'In progress',
    priority: 'High',
    isPrivate: false,
    comments: [
      {
        id: '9143',
        text: 'Это не срочно, но важно!',
        createdAt: new Date('2022-01-29T23:00:05'),
        author: 'Коршунов Илья',
      },
    ],
  },
  {
    id: '23',
    name: 'Сделать модалку',
    description: 'Сделать авторизацию пользователя на главной странице',
    createdAt: new Date('2023-02-20T23:00:00'),
    assignee: 'Симан',
    status: 'Complete',
    priority: 'High',
    isPrivate: false,
    comments: [
      {
        id: '9129',
        text: 'Это не срочно, но важно!',
        createdAt: new Date('2023-01-20T23:00:05'),
        author: 'Коршунов Илья',
      },
      {
        id: '9130',
        text: 'Не забудь проо логотип!',
        createdAt: new Date('2023-02-15T23:00:05'),
        author: 'Варан Саша',
      },
    ],
  },
  {
    id: '24',
    name: 'Сделать страницу гостя',
    description: 'Сделать страницу админа для администрирования сайта',
    createdAt: new Date('2023-01-20T23:00:00'),
    assignee: 'Горян',
    status: 'In progress',
    priority: 'Low',
    isPrivate: false,
    comments: [
      {
        id: '9135',
        text: 'Это не срочно, но важно!',
        createdAt: new Date('2023-01-20T23:00:05'),
        author: 'Коршунов Илья',
      },
    ],
  },
  {
    id: '25',
    name: 'Сделать страницу загрузки',
    description: 'Сделать страницу 404',
    createdAt: new Date('2023-03-20T23:00:00'),
    assignee: 'Ткачук',
    status: 'To Do',
    priority: 'Medium',
    isPrivate: true,
    comments: [
      {
        id: '9136',
        text: 'Это не срочно, но важно!',
        createdAt: new Date('2023-03-20T23:00:05'),
        author: 'Коршунов Илья',
      },
    ],
  },
  {
    id: '26',
    name: 'Разработать search',
    description: 'Разработать header для всех страниц',
    createdAt: new Date('2022-12-22T23:00:00'),
    assignee: 'Шук',
    status: 'To Do',
    priority: 'Low',
    isPrivate: false,
    comments: [
      {
        id: '9137',
        text: 'Это не срочно, но важно!',
        createdAt: new Date('2022-12-25T23:00:05'),
        author: 'Коршунов Илья',
      },
    ],
  },
  {
    id: '27',
    name: 'Разработать footer-light',
    description: 'Разработать footer для всех страниц',
    createdAt: new Date('2022-12-25T23:00:00'),
    assignee: 'Сидоренко',
    status: 'To Do',
    priority: 'Medium',
    isPrivate: false,
    comments: [
      {
        id: '9138',
        text: 'Это не срочно, но важно!',
        createdAt: new Date('2022-12-25T23:00:05'),
        author: 'Коршунов Илья',
      },
    ],
  },
  {
    id: '28',
    name: 'Разработать navigation-aside',
    description: 'Разработать navigation для всех страниц',
    createdAt: new Date('2022-12-27T23:00:00'),
    assignee: 'Сидоренко',
    status: 'In progress',
    priority: 'High',
    isPrivate: false,
    comments: [
      {
        id: '9139',
        text: 'Это не срочно, но важно!',
        createdAt: new Date('2022-12-27T23:00:05'),
        author: 'Коршунов Илья',
      },
    ],
  },
  {
    id: '29',
    name: 'Разработать aside-burger',
    description: 'Разработать aside для главной страницы',
    createdAt: new Date('2022-02-27T23:00:00'),
    assignee: 'Ткач',
    status: 'Complete',
    priority: 'Medium',
    isPrivate: false,
    comments: [
      {
        id: '9140',
        text: 'Это не срочно, но важно!',
        createdAt: new Date('2022-02-27T23:00:05'),
        author: 'Коршунов Илья',
      },
    ],
  },
  {
    id: '30',
    name: 'Сверстать confirm modal57',
    description:
     'Разработать confirm modal в соответствии с дизайном приложения',
    createdAt: new Date('2022-02-28T23:00:00'),
    assignee: 'Петров',
    status: 'To Do',
    priority: 'Low',
    isPrivate: true,
    comments: [
      {
        id: '9141',
        text: 'Это не срочно, но важно!',
        createdAt: new Date('2022-02-29T23:00:05'),
        author: 'Коршунов Илья',
      },
    ],
  },
  {
    id: '31',
    name: 'Сверстать главную страницу USERA',
    description:
     'Сверстать главную страницу в соответствии с дизайном приложения',
    createdAt: new Date('2022-01-28T23:00:00'),
    assignee: 'Петров',
    status: 'To Do',
    priority: 'Medium',
    isPrivate: true,
    comments: [
      {
        id: '9142',
        text: 'Это не срочно, но важно!',
        createdAt: new Date('2022-01-29T23:00:05'),
        author: 'Коршунов Илья',
      },
    ],
  },
  {
    id: '32',
    name: 'Создать логотип приложения',
    description: 'Формат изображения – svg, размеры - 100х100px',
    createdAt: new Date('2023-03-09T23:00:00'),
    assignee: 'Иванов',
    status: 'To Do',
    priority: 'High',
    isPrivate: false,
    comments: [
      {
        id: '912',
        text: 'Будет сделано!',
        createdAt: new Date('2023-03-09T23:00:00'),
        author: 'Иванов',
      },
    ],
  },
  {
    id: '33',
    name: 'Создать логотип приложения',
    description: 'Формат изображения – svg, размеры - 100х100px',
    createdAt: new Date('2023-03-09T23:00:00'),
    assignee: 'Иванов',
    status: 'Complete',
    priority: 'High',
    isPrivate: false,
    comments: [
      {
        id: '912',
        text: 'Будет сделано!',
        createdAt: new Date('2023-03-09T23:00:00'),
        author: 'Иванов',
      },
    ],
  },
  {
    id: '34',
    name: 'Переименовать константу DELAY_TIME ',
    description:
     'Необходимо переименовать константу с DELAY_TIME на DELAY_API_TIME',
    createdAt: new Date('2023-03-09T23:00:00'),
    assignee: 'Иванов',
    status: 'To Do',
    priority: 'High',
    isPrivate: false,
    comments: [
      {
        id: '912',
        text: 'Будет сделано!',
        createdAt: new Date('2023-03-09T23:00:00'),
        author: 'Иванов',
      },
    ],
  },
  {
    id: '35',
    name: 'Разработать дизайн ',
    description: 'Необходимо разработать дизайн приложения',
    createdAt: new Date('2023-02-09T23:00:00'),
    assignee: 'Петров',
    status: 'In progress',
    priority: 'Low',
    isPrivate: true,
    comments: [
      {
        id: '9120',
        text: 'Будет сделано!',
        createdAt: new Date('2023-02-09T23:00:05'),
        author: 'Петров',
      },
    ],
  },
  {
    id: '36',
    name: 'Разработать бургер-меню',
    description: 'Разработать бургер-меню',
    createdAt: new Date('2023-01-09T23:00:00'),
    assignee: 'Коршунов',
    status: 'In progress',
    priority: 'Medium',
    isPrivate: false,
    comments: [
      {
        id: '9121',
        text: 'Ok',
        createdAt: new Date('2023-01-09T23:00:05'),
        author: 'Коршунов',
      },
    ],
  },
  {
    id: '37',
    name: 'Разработать модалку',
    description: 'Сделать модалку',
    createdAt: new Date('2023-01-12T23:00:00'),
    assignee: 'Ермолаева',
    status: 'Complete',
    priority: 'Low',
    isPrivate: false,
    comments: [
      {
        id: '9122',
        text: 'Срочно!',
        createdAt: new Date('2023-01-12T23:00:05'),
        author: 'Коршунов',
      },
    ],
  },
  {
    id: '38',
    name: 'Протестировать бургер-меню',
    description: 'Протестировать бургер-меню на разных разрешениях',
    createdAt: new Date('2023-01-15T23:00:00'),
    assignee: 'Буян',
    status: 'To Do',
    priority: 'Low',
    isPrivate: true,
    comments: [
      {
        id: '9123',
        text: 'Это не срочно, но важно!',
        createdAt: new Date('2023-01-15T23:00:05'),
        author: 'Коршунов',
      },
    ],
  },
  {
    id: '39',
    name: 'Сделать адаптив',
    description: 'Сделать адаптивную версию дизайна',
    createdAt: new Date('2023-02-15T23:00:00'),
    assignee: 'Варан',
    status: 'In progress',
    priority: 'Medium',
    isPrivate: true,
    comments: [
      {
        id: '9124',
        text: 'Это не срочно, но важно!',
        createdAt: new Date('2023-01-15T23:00:05'),
        author: 'Коршунов',
      },
      {
        id: '9125',
        text: 'Не забудь проо логотип!',
        createdAt: new Date('2023-02-15T23:00:05'),
        author: 'Варан',
      },
    ],
  },
  {
    id: '40',
    name: 'Разработать слайдер',
    description: 'Сделать слайдер под фотографии',
    createdAt: new Date('2023-02-11T23:00:00'),
    assignee: 'Белусь',
    status: 'To Do',
    priority: 'Medium',
    isPrivate: false,
    comments: [
      {
        id: '912',
        text: 'Это не срочно, но важно!',
        createdAt: new Date('2023-01-12T23:00:05'),
        author: 'Коршунов Илья',
      },
      {
        id: '912',
        text: 'Не забудь про новые форматы!',
        createdAt: new Date('2023-02-15T23:00:05'),
        author: 'Варан Саша',
      },
    ],
  },
  {
    id: '41',
    name: 'Разработать пагинацию',
    description: 'Сделать пагинацию основной страницы',
    createdAt: new Date('2023-01-19T23:00:00'),
    assignee: 'Варяг',
    status: 'In progress',
    priority: 'Low',
    isPrivate: true,
    comments: [
      {
        id: '912',
        text: 'Будет сделано!',
        createdAt: new Date('2023-03-09T23:00:05'),
        author: 'Иванов',
      },
    ],
  },
  {
    id: '42',
    name: 'Сделать авторизацию',
    description: 'Сделать авторизацию пользователя на главной странице',
    createdAt: new Date('2023-02-20T23:00:00'),
    assignee: 'Симан',
    status: 'Complete',
    priority: 'High',
    isPrivate: false,
    comments: [
      {
        id: '9129',
        text: 'Это не срочно, но важно!',
        createdAt: new Date('2023-01-20T23:00:05'),
        author: 'Коршунов Илья',
      },
      {
        id: '9130',
        text: 'Не забудь проо логотип!',
        createdAt: new Date('2023-02-15T23:00:05'),
        author: 'Варан Саша',
      },
    ],
  },
  {
    id: '43',
    name: 'Сделать страницу админа',
    description: 'Сделать страницу админа для администрирования сайта',
    createdAt: new Date('2023-01-20T23:00:00'),
    assignee: 'Горян',
    status: 'In progress',
    priority: 'Low',
    isPrivate: false,
    comments: [
      {
        id: '9135',
        text: 'Это не срочно, но важно!',
        createdAt: new Date('2023-01-20T23:00:05'),
        author: 'Коршунов Илья',
      },
    ],
  },
  {
    id: '44',
    name: 'Сделать страницу 404',
    description: 'Сделать страницу 404',
    createdAt: new Date('2023-03-20T23:00:00'),
    assignee: 'Ткачук',
    status: 'To Do',
    priority: 'Medium',
    isPrivate: true,
    comments: [
      {
        id: '9136',
        text: 'Это не срочно, но важно!',
        createdAt: new Date('2023-03-20T23:00:05'),
        author: 'Коршунов Илья',
      },
    ],
  },
  {
    id: '45',
    name: 'Разработать header',
    description: 'Разработать header для всех страниц',
    createdAt: new Date('2022-12-22T23:00:00'),
    assignee: 'Шук',
    status: 'To Do',
    priority: 'Low',
    isPrivate: false,
    comments: [
      {
        id: '9137',
        text: 'Это не срочно, но важно!',
        createdAt: new Date('2022-12-25T23:00:05'),
        author: 'Коршунов Илья',
      },
    ],
  },
  {
    id: '46',
    name: 'Разработать footer',
    description: 'Разработать footer для всех страниц',
    createdAt: new Date('2022-12-25T23:00:00'),
    assignee: 'Сидоренко',
    status: 'To Do',
    priority: 'Medium',
    isPrivate: false,
    comments: [
      {
        id: '9138',
        text: 'Это не срочно, но важно!',
        createdAt: new Date('2022-12-25T23:00:05'),
        author: 'Коршунов Илья',
      },
    ],
  },
  {
    id: '47',
    name: 'Разработать navigation',
    description: 'Разработать navigation для всех страниц',
    createdAt: new Date('2022-12-27T23:00:00'),
    assignee: 'Сидоренко',
    status: 'In progress',
    priority: 'High',
    isPrivate: false,
    comments: [
      {
        id: '9139',
        text: 'Это не срочно, но важно!',
        createdAt: new Date('2022-12-27T23:00:05'),
        author: 'Коршунов Илья',
      },
    ],
  },
  {
    id: '48',
    name: 'Разработать aside',
    description: 'Разработать aside для главной страницы',
    createdAt: new Date('2022-02-27T23:00:00'),
    assignee: 'Ткач',
    status: 'Complete',
    priority: 'Medium',
    isPrivate: false,
    comments: [
      {
        id: '9140',
        text: 'Это не срочно, но важно!',
        createdAt: new Date('2022-02-27T23:00:05'),
        author: 'Коршунов Илья',
      },
    ],
  },
  {
    id: '49',
    name: 'Сверстать confirm modal',
    description:
     'Разработать confirm modal в соответствии с дизайном приложения',
    createdAt: new Date('2022-02-28T23:00:00'),
    assignee: 'Петров',
    status: 'To Do',
    priority: 'Low',
    isPrivate: true,
    comments: [
      {
        id: '9141',
        text: 'Это не срочно, но важно!',
        createdAt: new Date('2022-02-29T23:00:05'),
        author: 'Коршунов Илья',
      },
    ],
  },
  {
    id: '50',
    name: 'Сверстать главную страницу',
    description:
     'Сверстать главную страницу в соответствии с дизайном приложения',
    createdAt: new Date('2022-01-28T23:00:00'),
    assignee: 'Петров',
    status: 'To Do',
    priority: 'Medium',
    isPrivate: true,
    comments: [
      {
        id: '9142',
        text: 'Это не срочно, но важно!',
        createdAt: new Date('2022-01-29T23:00:05'),
        author: 'Коршунов Илья',
      },
    ],
  },
  {
    id: '51',
    name: 'Сверстать страницу регистрации',
    description:
     'Сверстать страницу регистрации в соответствии с дизайном приложения',
    createdAt: new Date('2022-01-29T23:00:00'),
    assignee: 'Васильев',
    status: 'In progress',
    priority: 'High',
    isPrivate: false,
    comments: [
      {
        id: '9143',
        text: 'Это не срочно, но важно!',
        createdAt: new Date('2022-01-29T23:00:05'),
        author: 'Коршунов Илья',
      },
    ],
  },
  {
    id: '52',
    name: 'Проверить макет на соответствие ТЗ',
    description: 'Проверить все страницы макета на соответствие ТЗ ',
    createdAt: new Date('2022-01-30T23:00:00'),
    assignee: 'Васильев',
    status: 'Complete',
    priority: 'High',
    isPrivate: false,
    comments: [
      {
        id: '912',
        text: 'Будет сделано!',
        createdAt: new Date('2023-03-09T23:00:05'),
        author: 'Иванов',
      },
    ],
  },
  {
    id: '53',
    name: 'Проверить макет ',
    description: 'Проверить все страницы макета',
    createdAt: new Date('2022-01-30T23:00:00'),
    assignee: 'Васильев',
    status: 'Complete',
    priority: 'Low',
    isPrivate: false,
    comments: [
      {
        id: '912',
        text: 'Будет сделано!',
        createdAt: new Date('2023-03-09T23:00:05'),
        author: 'Иванов',
      },
    ],
  },
  {
    id: '54',
    name: 'Сверстать страницу авторизации',
    description:
     'Сверстать страницу авторизации',
    createdAt: new Date('2022-01-29T23:00:00'),
    assignee: 'Васильев',
    status: 'In progress',
    priority: 'High',
    isPrivate: false,
    comments: [
      {
        id: '9143',
        text: 'Это не срочно, но важно!',
        createdAt: new Date('2022-01-29T23:00:05'),
        author: 'Коршунов Илья',
      },
    ],
  },
  {
    id: '55',
    name: 'Сделать модалку',
    description: 'Сделать авторизацию пользователя на главной странице',
    createdAt: new Date('2023-02-20T23:00:00'),
    assignee: 'Симан',
    status: 'Complete',
    priority: 'High',
    isPrivate: false,
    comments: [
      {
        id: '9129',
        text: 'Это не срочно, но важно!',
        createdAt: new Date('2023-01-20T23:00:05'),
        author: 'Коршунов Илья',
      },
      {
        id: '9130',
        text: 'Не забудь проо логотип!',
        createdAt: new Date('2023-02-15T23:00:05'),
        author: 'Варан Саша',
      },
    ],
  },
  {
    id: '56',
    name: 'Сделать страницу гостя',
    description: 'Сделать страницу админа для администрирования сайта',
    createdAt: new Date('2023-01-20T23:00:00'),
    assignee: 'Горян',
    status: 'In progress',
    priority: 'Low',
    isPrivate: false,
    comments: [
      {
        id: '9135',
        text: 'Это не срочно, но важно!',
        createdAt: new Date('2023-01-20T23:00:05'),
        author: 'Коршунов Илья',
      },
    ],
  },
  {
    id: '57',
    name: 'Сделать страницу загрузки',
    description: 'Сделать страницу 404',
    createdAt: new Date('2023-03-20T23:00:00'),
    assignee: 'Ткачук',
    status: 'To Do',
    priority: 'Medium',
    isPrivate: true,
    comments: [
      {
        id: '9136',
        text: 'Это не срочно, но важно!',
        createdAt: new Date('2023-03-20T23:00:05'),
        author: 'Коршунов Илья',
      },
    ],
  },
  {
    id: '58',
    name: 'Разработать search',
    description: 'Разработать header для всех страниц',
    createdAt: new Date('2022-12-22T23:00:00'),
    assignee: 'Шук',
    status: 'To Do',
    priority: 'Low',
    isPrivate: false,
    comments: [
      {
        id: '9137',
        text: 'Это не срочно, но важно!',
        createdAt: new Date('2022-12-25T23:00:05'),
        author: 'Коршунов Илья',
      },
    ],
  },
  {
    id: '59',
    name: 'Разработать footer-light',
    description: 'Разработать footer для всех страниц',
    createdAt: new Date('2022-12-25T23:00:00'),
    assignee: 'Сидоренко',
    status: 'To Do',
    priority: 'Medium',
    isPrivate: false,
    comments: [
      {
        id: '9138',
        text: 'Это не срочно, но важно!',
        createdAt: new Date('2022-12-25T23:00:05'),
        author: 'Коршунов Илья',
      },
    ],
  },
  {
    id: '60',
    name: 'Разработать navigation-aside',
    description: 'Разработать navigation для всех страниц',
    createdAt: new Date('2022-12-27T23:00:00'),
    assignee: 'Сидоренко',
    status: 'In progress',
    priority: 'High',
    isPrivate: false,
    comments: [
      {
        id: '9139',
        text: 'Это не срочно, но важно!',
        createdAt: new Date('2022-12-27T23:00:05'),
        author: 'Коршунов Илья',
      },
    ],
  },
  {
    id: '61',
    name: 'Разработать aside-burger',
    description: 'Разработать aside для главной страницы',
    createdAt: new Date('2022-02-27T23:00:00'),
    assignee: 'Ткач',
    status: 'Complete',
    priority: 'Medium',
    isPrivate: false,
    comments: [
      {
        id: '9140',
        text: 'Это не срочно, но важно!',
        createdAt: new Date('2022-02-27T23:00:05'),
        author: 'Коршунов Илья',
      },
    ],
  },
  {
    id: '62',
    name: 'Сверстать confirm modal57',
    description:
     'Разработать confirm modal в соответствии с дизайном приложения',
    createdAt: new Date('2022-02-28T23:00:00'),
    assignee: 'Петров',
    status: 'To Do',
    priority: 'Low',
    isPrivate: true,
    comments: [
      {
        id: '9141',
        text: 'Это не срочно, но важно!',
        createdAt: new Date('2022-02-29T23:00:05'),
        author: 'Коршунов Илья',
      },
    ],
  },
  {
    id: '63',
    name: 'Сверстать главную страницу USERA',
    description:
     'Сверстать главную страницу в соответствии с дизайном приложения',
    createdAt: new Date('2022-01-28T23:00:00'),
    assignee: 'Петров',
    status: 'To Do',
    priority: 'Medium',
    isPrivate: true,
    comments: [
      {
        id: '9142',
        text: 'Это не срочно, но важно!',
        createdAt: new Date('2022-01-29T23:00:05'),
        author: 'Коршунов Илья',
      },
    ],
  },
];
export default arrTasks;
