const arrUsers = [
  {
    id: '1',
    firstName: 'Петя',
    login: 'IvaPet',
    password: '101SS!!2Sh',
    avatar: './assets/icon/vue-color-avatar0.svg',
  },
  {
    id: '2',
    firstName: 'Вася',
    login: 'VaPet',
    password: '10103#ffdeS',
    avatar: './assets/icon/vue-color-avatar1.svg',
  },
  {
    id: '3',
    firstName: 'Илья',
    login: 'IKo',
    password: '555h%hDf',
    avatar: './assets/icon/vue-color-avatar2.svg',
  },
  {
    id: '4',
    firstName: 'Оля',
    login: 'Oeret',
    password: '65jh%hH',
    avatar: './assets/icon/vue-color-avatar3.svg',
  },
  {
    id: '5',
    firstName: 'Саша',
    login: 'Head',
    password: '65G#Ghk22',
    avatar: './assets/icon/vue-color-avatar4.svg',
  },
  {
    id: '6',
    firstName: 'Катя',
    login: 'Body',
    password: '635F%F22gg',
    avatar: './assets/icon/vue-color-avatar2.svg',
  },
  {
    id: '7',
    firstName: 'Олег',
    login: 'Sem',
    password: 'Hgf225%54',
    avatar: './assets/icon/vue-color-avatar0.svg',
  },
  {
    id: '8',
    firstName: 'Дима',
    login: 'Tom',
    password: 'KJhgf^52263',
    avatar: './assets/icon/vue-color-avatar1.svg',
  },
  {
    id: '9',
    firstName: 'Таня',
    login: 'First',
    password: 'Hjg&25226',
    avatar: './assets/icon/vue-color-avatar3.svg',
  },
  {
    id: '10',
    firstName: 'Макс',
    login: 'Second',
    password: 'FG22Kolj&526',
    avatar: './assets/icon/vue-color-avatar4.svg',
  },
  {
    id: '11',
    firstName: 'Глеб',
    login: 'Jyyyek',
    password: 'dfgk2kHff&H554',
    avatar: './assets/icon/vue-color-avatar0.svg',
  },
  {
    id: '12',
    firstName: 'Стас',
    login: 'Vorobej',
    password: 'dfgk2kH&H554',
    avatar: './assets/icon/vue-color-avatar1.svg',
  },
  {
    id: '13',
    firstName: 'Алекс',
    login: 'Aleks',
    password: 'fjkkSSk222d#k',
    avatar: './assets/icon/vue-color-avatar1.svg',
  },
  {
    id: '14',
    firstName: 'Кирилл',
    login: 'KirBoss',
    password: 'FFhhh#hgjk256',
    avatar: './assets/icon/vue-color-avatar1.svg',
  },
];
export default arrUsers;
