const arrUsers = [
  {
    id: '1',
    firstName: 'Петя',
    lastName: 'Иванов',
    login: 'IvaPet',
    password: '101SS!!2Sh',
    email: 'pet@mail.ru',
  },
  {
    id: '2',
    firstName: 'Вася',
    lastName: 'Петров',
    login: 'VaPet',
    password: '10103#ffdeS',
    email: 'fjfi@mail.ru',
  },
  {
    id: '3',
    firstName: 'Илья',
    lastName: 'Коршунов',
    login: 'IKo',
    password: '555h%hDf',
    email: 'fjd@mail.ru',
  },
  {
    id: '4',
    firstName: 'Оля',
    lastName: 'Ермолаева',
    login: 'Oeret',
    password: '65jh%hH',
    email: 'gjdd@mail.ru',
  },
  {
    id: '5',
    firstName: 'Саша',
    lastName: 'Буян',
    login: 'Head',
    password: '65G#Ghk22',
    email: 'ffgh@mail.ru',
  },
  {
    id: '6',
    firstName: 'Катя',
    lastName: 'Варан',
    login: 'Body',
    password: '635F%F22gg',
    email: 'glfd@mail.ru',
  },
  {
    id: '7',
    firstName: 'Олег',
    lastName: 'Белусь',
    login: 'Sem',
    password: 'Hgf225%54',
    email: 'fgth@mail.ru',
  },
  {
    id: '8',
    firstName: 'Дима',
    lastName: 'Варяг',
    login: 'Tom',
    password: 'KJhgf^52263',
    email: 'gnn@mail.ru',
  },
  {
    id: '9',
    firstName: 'Таня',
    lastName: 'Симан',
    login: 'First',
    password: 'Hjg&25226',
    email: 'kgiu@mail.ru',
  },
  {
    id: '10',
    firstName: 'Макс',
    lastName: 'Горян',
    login: 'Second',
    password: 'FG22Kolj&526',
    email: 'nhn@mail.ru',
  },
  {
    id: '11',
    firstName: 'Глеб',
    lastName: 'Ткачук',
    login: 'Jlllek',
    password: '465G22&Ghk',
    email: 'nhtn@mail.ru',
  },
  {
    id: '12',
    firstName: 'Стас',
    lastName: 'Шук',
    login: 'Vorobej',
    password: 'dfgk2kH&H554',
    email: 'nhyut@mail.ru',
  },
  {
    id: '13',
    firstName: 'Алекс',
    lastName: 'Сидоренко',
    login: 'Aleks',
    password: 'fjkkkSS222d#k',
    email: 'nhnyt@mail.ru',
  },
  {
    id: '14',
    firstName: 'Кирилл',
    lastName: 'Васильев',
    login: 'KirBoss',
    password: 'FFhhh#hgjk256',
    email: 'nyum@mail.ru',
  },
];
export default arrUsers;
